### ISSUE TITLE
How to config the .env.example file

### ISSUE THREAD

**Issue by 160905** [RiP3rQ/ui-butler-turborepo#85]
I just want to running your project in my local env, and I have already prepared services such as the PostgreSQL database and redis service.
How should I correctly configure the connection string of db and redis.

**Comment by RiP3rQ** [comment]
You can generate a docker-compose.yml file like that for postgres (+ add redis service if you want to run redis locally) ->

```yml
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: auth-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./postgres-data:/var/db/postgresql/data
```

And then you can use it in the env file like -> 

```env
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/db
```

There is many tutorials on the internet how to do this properly or you can just ask chatgpt.
